(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const STORE = {
    get(k, d) { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : d; } catch { return d; } },
    set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} }
  };
  const state = {
    market: [], marketMeta: {}, byTicker: new Map(),
    watch: STORE.get('mt_watch_v2', ['NVDA','AAPL','MSFT','AMZN','TSLA','AMD']),
    portfolio: STORE.get('mt_port_v2', []),
    view: 'overview', selected: null, insiderMode: 'buys', insiderData: {}, gurus: [], guruMode: 'all', chartInterval: '5', chartIndicator: STORE.get('mt_chart_indicator','VOL'), detailBars: [], detailIntraday: [], chart: null,
    compare: STORE.get('mt_compare_v1', ['NVDA','AMD','INTC']), insiderSignals: new Map(), guruSignals: new Map(), fundamentalPeriod: 'quarterly', detailFundamentals: null,
  };
  const cache = new Map();
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const ok = v => Number.isFinite(Number(v));
  const money = v => ok(v) ? new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'USD',minimumFractionDigits:Math.abs(v)<1?4:2,maximumFractionDigits:Math.abs(v)<1?4:2}).format(v) : '—';
  const num = (v,d=2) => ok(v) ? new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v) : '—';
  const compact = v => ok(v) ? new Intl.NumberFormat('cs-CZ',{notation:'compact',maximumFractionDigits:1}).format(v) : '—';
  const pct = v => ok(v) ? `${Number(v)>0?'+':''}${num(v,2)} %` : '—';
  const cls = v => Number(v)>0?'up':Number(v)<0?'down':'flat';
  const date = v => v ? new Date(v).toLocaleDateString('cs-CZ') : '—';
  const dateTime = v => v ? new Date(v).toLocaleString('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}) : '—';
  const rel = v => { const n=Number(v); return Number.isFinite(n)?`${num(n,2)}×`:'—'; };
  const signalClass = s => s>=75?'high':s>=50?'mid':'';
  const toast = text => { const el=$('#toast'); el.textContent=text; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),2200); };
  async function data(name, fresh = false) {
    if (!fresh && cache.has(name)) return cache.get(name);
    const url = `data/${name}?v=${Math.floor(Date.now()/300000)}`;
    const p = fetch(url,{cache:'no-cache'}).then(r => { if(!r.ok) throw new Error(`${name}: ${r.status}`); return r.json(); });
    cache.set(name,p); try { return await p; } catch(e) { cache.delete(name); throw e; }
  }

  function setView(view) {
    state.view=view;
    $$('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));
    $$('.main-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
    if(view==='insiders') loadInsiders(); if(view==='gurus') loadGurus(); if(view==='compare') renderCompare(); if(view==='portfolio') renderPortfolio();
    if(view!=='detail') location.hash = view==='overview'?'prehled':view;
    window.scrollTo({top:0,behavior:'smooth'});
  }
  $$('.main-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
  $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
  $('#backBtn').addEventListener('click',()=>setView('overview'));

  function saveWatch(){ state.watch=[...new Set(state.watch)]; STORE.set('mt_watch_v2',state.watch); renderWatch(); renderStocks(); renderMetrics(); }
  function toggleWatch(ticker){ ticker=ticker.toUpperCase(); const i=state.watch.indexOf(ticker); if(i>=0){state.watch.splice(i,1);toast(`${ticker} odebrána ze sledovaných`);}else{state.watch.push(ticker);toast(`${ticker} přidána do sledovaných`);} saveWatch(); if(state.selected===ticker) renderDetailWatch(); }
  function renderWatch(){
    const box=$('#watchlist'); if(!state.watch.length){box.innerHTML='<div class="empty-state">Watchlist je prázdný.</div>';return;}
    box.innerHTML=state.watch.map(t=>{const s=state.byTicker.get(t);return `<div class="watch-row"><button class="open-stock" data-open="${esc(t)}"><b>${esc(t)}</b><small>${esc(s?.name||'Čekám na data')}</small></button><div class="quote-mini"><b>${money(s?.price)}</b><span class="${cls(s?.change)}">${pct(s?.change)}</span></div><button class="remove-watch" data-unwatch="${esc(t)}" aria-label="Odebrat ${esc(t)}">×</button></div>`;}).join('');
  }
  $('#addWatchBtn').addEventListener('click',()=>{const s=$('#sideSearch');s.hidden=!s.hidden;if(!s.hidden)$('#watchInput').focus();});
  function addWatchInput(){const t=$('#watchInput').value.trim().toUpperCase().replace(/[^A-Z0-9.\-]/g,'');if(!t)return;if(!state.byTicker.has(t)){toast('Tento ticker zatím není v tržním přehledu');return;}if(!state.watch.includes(t))state.watch.push(t);$('#watchInput').value='';saveWatch();}
  $('#watchAddConfirm').addEventListener('click',addWatchInput); $('#watchInput').addEventListener('keydown',e=>{if(e.key==='Enter')addWatchInput();});

  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  function yearPosition(s){return ok(s.price)&&ok(s.year_low)&&ok(s.year_high)&&s.year_high>s.year_low?clamp((s.price-s.year_low)/(s.year_high-s.year_low)*100,0,100):null;}
  function scoreBreakdown(s){
    const yp=yearPosition(s),change=Number(s.change)||0,rv=Number(s.rel_volume)||0;
    const insider=state.insiderSignals.get(s.ticker)||{count:Number(s.insider_buys)||0,people:0,value:0};
    const guru=state.guruSignals.get(s.ticker)||{new:0,add:0,cut:0,out:0};
    const trend=Math.round(clamp((yp??50)*.19+(change>0?5:1),0,25));
    const momentum=Math.round(clamp(10+change*1.8,0,20));
    const volume=Math.round(clamp(4+rv*7,0,20));
    const smart=Math.round(clamp(insider.count*4+insider.people*3+guru.new*5+guru.add*2-guru.cut*1.5-guru.out*3,0,25));
    const stability=Math.round(clamp(10-Math.max(0,Math.abs(change)-3)*.8,2,10));
    return {trend,momentum,volume,smart,stability,total:trend+momentum+volume+smart+stability,insider,guru,yearPosition:yp};
  }
  function scoreStock(s){return scoreBreakdown(s).total;}
  function scoreVerdict(s){const b=scoreBreakdown(s),parts=[];if(b.volume>=13)parts.push('neobvyklý objem');if(b.momentum>=15)parts.push('silné momentum');if(b.smart>=12)parts.push('aktivita chytrých peněz');if(b.trend>=20)parts.push('cena blízko ročního maxima');if(!parts.length)parts.push('zatím bez výrazného potvrzení');return `${b.total}/100 – ${parts.join(', ')}.`;}
  function renderMetrics(){
    const rows=state.market.filter(s=>ok(s.price)); if(!rows.length)return;
    const active=[...rows].sort((a,b)=>(b.volume||0)-(a.volume||0))[0];
    const unusual=[...rows].sort((a,b)=>(b.rel_volume||0)-(a.rel_volume||0))[0];
    const mover=[...rows].sort((a,b)=>Math.abs(b.change||0)-Math.abs(a.change||0))[0];
    const wset=new Set(state.watch),wrows=rows.filter(s=>wset.has(s.ticker)),buys=(wset.size?wrows:rows).reduce((n,s)=>n+(s.insider_buys||0),0),buysLabel=wset.size?'u sledovaných titulů':`u všech ${rows.length} titulů v přehledu`;
    $('#marketMetrics').innerHTML=`<article class="metric-card"><span>Nejvyšší objem</span><strong>${esc(active.ticker)}</strong><small>${compact(active.volume)} akcií</small></article><article class="metric-card"><span>Neobvyklý objem</span><strong>${esc(unusual.ticker)}</strong><small>${rel(unusual.rel_volume)} běžného objemu</small></article><article class="metric-card"><span>Největší pohyb</span><strong>${esc(mover.ticker)}</strong><small class="${cls(mover.change)}">${pct(mover.change)}</small></article><article class="metric-card metric-link" role="button" tabindex="0" data-open-buys aria-label="Zobrazit insider nákupy"><span>Insider nákupy <em class="metric-go">Zobrazit →</em></span><strong>${buys}</strong><small>${buysLabel}</small></article>`;
  }
  function filteredStocks(){
    const q=$('#stockSearch').value.trim().toLowerCase(), f=$('#stockFilter').value, sort=$('#stockSort').value;
    let rows=state.market.filter(s=>!q||`${s.ticker} ${s.name}`.toLowerCase().includes(q));
    if(f==='unusual')rows=rows.filter(s=>(s.rel_volume||0)>=1.5);if(f==='strong-volume')rows=rows.filter(s=>(s.rel_volume||0)>=2);if(f==='gainers')rows=rows.filter(s=>(s.change||0)>=2);if(f==='losers')rows=rows.filter(s=>(s.change||0)<=-2);if(f==='insider')rows=rows.filter(s=>(state.insiderSignals.get(s.ticker)?.count||s.insider_buys||0)>0);if(f==='high-score')rows=rows.filter(s=>scoreStock(s)>=70);if(f==='near-high')rows=rows.filter(s=>(yearPosition(s)||0)>=90);if(f==='watch')rows=rows.filter(s=>state.watch.includes(s.ticker));if(f==='assets')rows=rows.filter(s=>/-USD$/.test(s.ticker)||s.ticker==='VIX'||/ETF|Fund/i.test(s.name||''));
    const sorts={volume:(a,b)=>(b.volume||0)-(a.volume||0),relative:(a,b)=>(b.rel_volume||0)-(a.rel_volume||0),change:(a,b)=>(b.change||0)-(a.change||0),score:(a,b)=>scoreStock(b)-scoreStock(a),yearPosition:(a,b)=>(yearPosition(b)||0)-(yearPosition(a)||0)};
    return rows.sort(sorts[sort]||sorts.volume);
  }
  function renderStocks(){
    const rows=filteredStocks(), max=Math.max(1,...rows.map(s=>s.volume||0)); $('#stockEmpty').hidden=!!rows.length;
    $('#stockRows').innerHTML=rows.map(s=>{const score=scoreStock(s), watched=state.watch.includes(s.ticker);return `<tr><td><div class="stock-id"><span class="mini-logo">${esc(s.ticker.slice(0,2))}</span><button data-open="${esc(s.ticker)}"><b>${esc(s.ticker)}</b><small>${esc(s.name||'')}</small></button></div></td><td class="num"><b>${money(s.price)}</b></td><td class="num ${cls(s.change)}"><b>${pct(s.change)}</b></td><td class="num"><div class="volume-bar">${compact(s.volume)}<i style="--w:${Math.max(4,(s.volume||0)/max*100)}%"></i></div></td><td class="num ${Number(s.rel_volume)>=1.5?'up':''}">${rel(s.rel_volume)}</td><td class="num">${money(s.day_low)}–${money(s.day_high)}</td><td class="num"><button class="score-button" data-open="${esc(s.ticker)}" title="${esc(scoreVerdict(s))}"><span class="signal ${signalClass(score)}">${score}/100</span><small>${esc(scoreVerdict(s).split('–')[1]||'')}</small></button></td><td><button class="star-btn ${watched?'on':''}" data-watch="${esc(s.ticker)}" aria-label="${watched?'Odebrat':'Sledovat'} ${esc(s.ticker)}">${watched?'★':'☆'}</button></td></tr>`;}).join('');
  }
  ['stockSearch','stockFilter','stockSort'].forEach(id=>$('#'+id).addEventListener(id==='stockSearch'?'input':'change',renderStocks));
  function renderPulse(){const wanted=[['VIX','VIX'],['SPY','S&P 500 (SPY)'],['QQQ','Nasdaq (QQQ)'],['DIA','Dow (DIA)'],['IWM','Russell (IWM)'],['GLD','Zlato (GLD)'],['SLV','Stříbro (SLV)'],['USO','Ropa (USO)'],['BTC-USD','Bitcoin'],['ETH-USD','Ethereum']];const rows=wanted.map(([t,l])=>{const s=state.byTicker.get(t);return s?{...s,label:l}:null;}).filter(Boolean);$('#marketPulse').innerHTML=rows.length?rows.map(s=>`<button class="pulse-row" type="button" data-open="${esc(s.ticker)}" title="${esc(s.name||s.ticker)}"><b>${esc(s.label)}</b><span>${s.ticker==='VIX'?num(s.price,2):money(s.price)}</span><span class="${s.ticker==='VIX'?cls(-(s.change||0)):cls(s.change)}">${pct(s.change)}</span></button>`).join('')+'<p class="pulse-note">VIX roste, když má trh strach. Pod 15 klid, nad 25 nervozita.</p>':'<div class="empty-state">Indexy se připravují.</div>';}

  async function renderHighlights(){
    try{
      const [buys,gurus,f13d]=await Promise.all([data('feed-buys.json'),data('gurus.json'),data('f13d.json').catch(()=>[])]);state.insiderData.buys=buys||[];state.insiderData.f13d=f13d||[];state.gurus=gurus||[];buildSignalIndexes();
      const top=[...(buys||[])].sort((a,b)=>(b.sc||0)-(a.sc||0)||((b.s||0)*(b.p||0))-((a.s||0)*(a.p||0))).slice(0,5);
      $('#topInsiders').innerHTML=top.length?top.map(r=>`<div class="compact-item"><span class="badge buy">${esc(r.t||'—')}</span><div><b>${esc(title(r.o||'Neznámý insider'))}</b><small>${esc(r.r||r.i||'')} · obchod ${date(r.d)}</small></div><b>${compact((r.s||0)*(r.p||0))} $</b></div>`).join(''):'<div class="empty-state">Žádné nové nákupy.</div>';
      const moves=[];for(const g of gurus||[])for(const p of (g.pos||[]))if(['new','add','cut','out'].includes(p.ch))moves.push({g,p});moves.sort((a,b)=>(b.p.v||0)-(a.p.v||0));
      $('#topGurus').innerHTML=moves.length?moves.slice(0,5).map(({g,p})=>`<div class="compact-item"><span class="badge ${['new','add'].includes(p.ch)?'buy':'sell'}">${esc(p.t||'—')}</span><div><b>${esc(g.label||g.fund||'Investor')}</b><small>${esc(changeLabel(p.ch))} · stav ${date(g.period)}</small></div><b>${compact(p.v)} $</b></div>`).join(''):'<div class="empty-state">Data 13F se připravují.</div>';renderStocks();renderMetrics();if(state.view==='compare')renderCompare();
    }catch{$('#topInsiders').innerHTML=$('#topGurus').innerHTML='<div class="empty-state">Data se nepodařilo načíst.</div>';}
  }

  function buildSignalIndexes(){
    const insiders=new Map();for(const r of state.insiderData.buys||[]){if(!r.t)continue;const g=insiders.get(r.t)||{count:0,value:0,names:new Set(),people:0};g.count++;g.value+=(Number(r.s)||0)*(Number(r.p)||0);if(r.o)g.names.add(r.o);g.people=g.names.size;insiders.set(r.t,g);}state.insiderSignals=insiders;
    const gurus=new Map();for(const g of state.gurus||[])for(const p of g.pos||[]){if(!p.t)continue;const x=gurus.get(p.t)||{new:0,add:0,cut:0,out:0,value:0};if(Object.hasOwn(x,p.ch))x[p.ch]++;x.value+=Number(p.v)||0;gurus.set(p.t,x);}state.guruSignals=gurus;
  }

  async function openDetail(ticker){
    ticker=ticker.toUpperCase();state.selected=ticker;setView('detail');history.replaceState(null,'',`#${ticker}`);const s=state.byTicker.get(ticker)||{ticker,name:ticker};
    $('#detailTicker').textContent=ticker;$('#detailLogo').textContent=ticker.slice(0,2);$('#detailName').textContent=s.name||ticker;$('#detailPrice').textContent=money(s.price);$('#detailChange').textContent=pct(s.change);$('#detailChange').className=cls(s.change);$('#detailTime').textContent=`Tržní snapshot ${dateTime(state.marketMeta.updated)}`;renderDetailWatch();
    const yearPos=ok(s.year_high)&&ok(s.year_low)&&s.year_high!==s.year_low?((s.price-s.year_low)/(s.year_high-s.year_low)*100):null;
    $('#detailStats').innerHTML=`<div class="panel-head"><div><p class="eyebrow">KLÍČOVÉ HODNOTY</p><h2>${esc(ticker)}</h2></div></div><div class="stat-row"><span>Denní minimum</span><b>${money(s.day_low)}</b></div><div class="stat-row"><span>Denní maximum</span><b>${money(s.day_high)}</b></div><div class="stat-row"><span>Objem</span><b>${compact(s.volume)}</b></div><div class="stat-row"><span>20denní průměr</span><b>${compact(s.avg_volume)}</b></div><div class="stat-row"><span>Relativní objem</span><b>${rel(s.rel_volume)}</b></div><div class="stat-row"><span>52týdenní minimum</span><b>${money(s.year_low)}</b></div><div class="stat-row"><span>52týdenní maximum</span><b>${money(s.year_high)}</b></div><div class="stat-row"><span>Pozice v 52týdenním pásmu</span><b>${ok(yearPos)?num(yearPos,0)+' %':'—'}</b></div><div class="stat-row"><span>MarketTrace skóre</span><b>${scoreStock(s)}/100</b></div>`;
    renderScoreExplain(s);$('#eventTimeline').innerHTML='<div class="skeleton h40"></div>';$('#priceChart').innerHTML='<div class="skeleton chart-skeleton"></div>';$('#detailInsiders').innerHTML='<div class="skeleton h40"></div>';$('#fundamentalSummary').innerHTML=$('#valuationPanel').innerHTML=$('#riskPanel').innerHTML='<div class="skeleton h40"></div>';$('#fundamentalChart').innerHTML=$('#fundamentalTable').innerHTML='';
    try{const [bars,intraday,sec,fund,spy]=await Promise.all([data(`bars/${ticker}.json`),data(`intraday/${ticker}.json`).catch(()=>[]),data(`t/${ticker}.json`).catch(()=>null),data(`fundamentals/${ticker}.json`).catch(()=>null),data('bars/SPY.json').catch(()=>[])]);state.detailBars=bars||[];state.detailIntraday=intraday||[];state.detailFundamentals=fund;renderMarketChart(ticker);renderDetailInsiders(sec?.tx||[]);renderEvents(s,sec?.tx||[],bars||[],fund?.events||[]);renderFundamentals(fund,s);renderRiskPanel(bars||[],spy||[]);}catch{state.detailBars=[];state.detailIntraday=[];state.detailFundamentals=null;renderMarketChart(ticker);renderDetailInsiders([]);renderEvents(s,[],[]);renderFundamentals(null,s);renderRiskPanel([],[]);}
  }
  function renderScoreExplain(s){
    const b=scoreBreakdown(s),rows=[['Trend',b.trend,25],['Momentum',b.momentum,20],['Objem',b.volume,20],['Smart money',b.smart,25],['Stabilita',b.stability,10]];
    $('#scoreExplain').innerHTML=`<div class="panel-head"><div><p class="eyebrow">VYSVĚTLITELNÉ SKÓRE</p><h2>${esc(scoreVerdict(s))}</h2></div><span class="score-ring ${signalClass(b.total)}">${b.total}</span></div><div class="score-breakdown">${rows.map(([label,value,max])=>`<div class="score-part"><div><span>${label}</span><b>${value}/${max}</b></div><i><em style="--w:${value/max*100}%"></em></i></div>`).join('')}</div><p class="score-note">Skóre kombinuje trend, dnešní momentum, relativní objem a veřejná hlášení SEC/13F. Není to doporučení k nákupu.</p>`;
  }
  function renderEvents(s,trades,bars,filings=[]){
    const events=[];const rv=Number(s.rel_volume)||0,yp=yearPosition(s),ch=Number(s.change)||0;
    if(rv>=1.5)events.push({d:s.timestamp||state.marketMeta.updated,type:'volume',title:`Objem ${num(rv,2)}× nad běžným dnem`,text:`Zobchodováno ${compact(s.volume)} akcií.`});
    if(Math.abs(ch)>=2)events.push({d:s.timestamp||state.marketMeta.updated,type:ch>0?'buy':'sell',title:`Denní pohyb ${pct(ch)}`,text:ch>0?'Kupující dnes mají převahu.':'Prodejní tlak je dnes zvýšený.'});
    if(yp!==null&&yp>=90)events.push({d:s.timestamp||state.marketMeta.updated,type:'high',title:'Blízko 52týdenního maxima',text:`Cena je na ${num(yp,0)} % ročního pásma.`});
    for(const r of groupTrades(trades).filter(x=>['P','S'].includes(x.k)).slice(0,8)){const buy=r.k==='P';events.push({d:r.d||r.f,type:buy?'buy':'sell',title:`${buy?'Nákup':'Prodej'} insidera za ${compact(r.value||((r.s||0)*(r.p||0)))} $`,text:`${title(r.o||'Insider')} · ${r.r||r.i||'role neuvedena'}`,url:r.u});}
    for(const f of filings.slice(0,12)){const labels=(f.labels||[]).slice(1,3);events.push({d:f.filed||f.report,type:'filing',title:f.title||'Významná firemní událost',text:labels.length?labels.join(' · '):`Formulář ${f.form||'8-K'} zveřejněný společností.`,url:f.url});}
    if(Array.isArray(bars)&&bars.length>1){let best=null;for(let i=1;i<bars.length;i++){const prev=Number(bars[i-1]?.[4]),close=Number(bars[i]?.[4]);if(!prev||!close)continue;const move=(close/prev-1)*100;if(!best||Math.abs(move)>Math.abs(best.move))best={row:bars[i],move};}if(best&&Math.abs(best.move)>=5)events.push({d:best.row[0],type:best.move>0?'buy':'sell',title:`Největší denní pohyb období ${pct(best.move)}`,text:'Výrazná cenová událost v uložené historii.'});}
    events.sort((a,b)=>new Date(b.d)-new Date(a.d));$('#eventTimeline').innerHTML=events.length?events.slice(0,10).map(e=>`<article class="event-item"><span class="event-dot ${e.type}"></span><div><time>${date(e.d)}</time><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p>${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Hlášení SEC →</a>`:''}</div></article>`).join(''):'<div class="empty-state">Pro titul zatím nejsou dostupné výrazné události.</div>';
  }
  const ratioPct=v=>ok(v)?`${Number(v)>0?'+':''}${num(Number(v)*100,1)} %`:'—';
  const metricValue=(fund,key,period)=>fund?.series?.[key]?.[period]||[];
  function valueAt(rows,end){return rows.find(r=>r.end===end)?.value;}
  function renderFundamentals(fund,s){
    if(!fund){$('#fundamentalSummary').innerHTML='<div class="empty-state">Finanční výkazy se připraví při nejbližší serverové aktualizaci.</div>';$('#fundamentalChart').innerHTML='';$('#fundamentalTable').innerHTML='';$('#valuationPanel').innerHTML='<div class="panel-head"><div><p class="eyebrow">OCENĚNÍ</p><h2>Data se připravují</h2></div></div>';return renderValuation(null,s);}
    $('#fundamentalSource').textContent=fund.source||'Firemní výkazy';const t=fund.ttm||{},v=fund.valuation||{},latest=(fund.series?.revenue?.quarterly||[]).at(-1),previous=(fund.series?.revenue?.quarterly||[]).at(-5),growth=latest&&previous&&previous.value?latest.value/previous.value-1:v.revenue_growth_yoy;
    $('#fundamentalSummary').innerHTML=`<div><span>Tržby TTM</span><b>${compact(t.revenue)} $</b><small class="${cls(growth)}">meziročně ${ratioPct(growth)}</small></div><div><span>Čistý zisk TTM</span><b>${compact(t.net_income)} $</b><small>marže ${ratioPct(v.net_margin)}</small></div><div><span>Volné cash flow TTM</span><b>${compact(t.free_cash_flow)} $</b><small>${Number(t.free_cash_flow)>=0?'firma tvoří hotovost':'záporné cash flow'}</small></div><div><span>Provozní marže</span><b>${ratioPct(v.operating_margin)}</b><small>z výnosů společnosti</small></div>`;
    renderFundamentalPeriod();renderValuation(fund,s);
  }
  function renderFundamentalPeriod(){
    const fund=state.detailFundamentals;if(!fund)return;const period=state.fundamentalPeriod,rev=metricValue(fund,'revenue',period),inc=metricValue(fund,'net_income',period),fcfRows=metricValue(fund,'operating_cash',period),capex=metricValue(fund,'capex',period);const periods=[...new Set([...rev,...inc].map(r=>r.end))].sort().slice(-6),max=Math.max(1,...periods.map(end=>Math.max(Math.abs(valueAt(rev,end)||0),Math.abs(valueAt(inc,end)||0))));
    $('#fundamentalChart').innerHTML=periods.length?periods.map(end=>{const r=valueAt(rev,end)||0,n=valueAt(inc,end)||0;return `<div class="fund-group"><div class="fund-bars"><i class="revenue" style="--h:${Math.max(3,Math.abs(r)/max*100)}%" title="Tržby ${compact(r)} $"></i><i class="income ${n<0?'negative':''}" style="--h:${Math.max(3,Math.abs(n)/max*100)}%" title="Čistý zisk ${compact(n)} $"></i></div><small>${esc(period==='annual'?end.slice(0,4):end.slice(2,7).replace('-','/'))}</small></div>`;}).join(''):'<div class="empty-state">Pro toto období nejsou dostupná standardizovaná data.</div>';
    const rows=periods.slice().reverse().map(end=>{const cash=valueAt(fcfRows,end),cap=valueAt(capex,end),free=ok(cash)&&ok(cap)?cash-cap:null;return `<tr><td>${date(end)}</td><td>${compact(valueAt(rev,end))} $</td><td class="${cls(valueAt(inc,end))}">${compact(valueAt(inc,end))} $</td><td class="${cls(free)}">${compact(free)} $</td></tr>`;}).join('');
    $('#fundamentalTable').innerHTML=rows?`<table><thead><tr><th>Období</th><th>Tržby</th><th>Čistý zisk</th><th>Volné cash flow</th></tr></thead><tbody>${rows}</tbody></table>`:'';
  }
  $$('[data-fund-period]').forEach(b=>b.addEventListener('click',()=>{state.fundamentalPeriod=b.dataset.fundPeriod;$$('[data-fund-period]').forEach(x=>x.classList.toggle('active',x===b));renderFundamentalPeriod();}));
  function renderValuation(fund,s){
    if(!fund){$('#valuationPanel').innerHTML='<div class="panel-head"><div><p class="eyebrow">OCENĚNÍ A KVALITA</p><h2>Čekám na SEC data</h2></div></div><div class="empty-state">Server zatím tento finanční snapshot nevytvořil.</div>';return;}
    const v=fund?.valuation||{},t=fund?.ttm||{},shares=fund?.instant?.shares?.value,cap=ok(s?.price)&&ok(shares)?Number(s.price)*Number(shares):v.market_cap,pe=ok(t.eps_diluted)&&Number(t.eps_diluted)>0?Number(s.price)/Number(t.eps_diluted):v.pe_ttm,ps=ok(cap)&&ok(t.revenue)?cap/t.revenue:v.ps_ttm,fcfy=ok(t.free_cash_flow)&&ok(cap)?t.free_cash_flow/cap:v.fcf_yield,netDebt=v.net_debt;
    let health=0,reasons=[];if(Number(v.revenue_growth_yoy)>0){health+=20;reasons.push('rostoucí tržby');}if(Number(t.free_cash_flow)>0){health+=25;reasons.push('kladné FCF');}if(Number(v.operating_margin)>.15){health+=20;reasons.push('silná provozní marže');}else if(Number(v.operating_margin)>0)health+=10;if(Number(v.roe)>.15)health+=20;else if(Number(v.roe)>0)health+=10;if(ok(netDebt)&&Number(netDebt)<=0){health+=15;reasons.push('čistá hotovost');}else if(ok(netDebt)&&ok(t.free_cash_flow)&&t.free_cash_flow>0&&netDebt/t.free_cash_flow<3)health+=10;health=Math.min(100,health);
    const tone=health>=70?'high':health>=45?'mid':'';
    $('#valuationPanel').innerHTML=`<div class="panel-head"><div><p class="eyebrow">OCENĚNÍ A KVALITA</p><h2>${fund?'Jak drahá a zdravá je firma':'Čekám na SEC data'}</h2></div>${fund?`<span class="signal ${tone}">${health}/100</span>`:''}</div><div class="valuation-grid"><div><span>P/E (TTM)</span><b>${ok(pe)&&pe>0?num(pe,1)+'×':'—'}</b><small>${ok(pe)?pe<18?'nižší násobek':pe>35?'vysoký násobek':'střední pásmo':'zisk není kladný / chybí'}</small></div><div><span>P/S (TTM)</span><b>${ok(ps)?num(ps,1)+'×':'—'}</b><small>cena vůči tržbám</small></div><div><span>FCF výnos</span><b>${ratioPct(fcfy)}</b><small>cash flow vůči hodnotě firmy</small></div><div><span>ROE</span><b>${ratioPct(v.roe)}</b><small>návratnost kapitálu</small></div><div><span>Tržní hodnota</span><b>${compact(cap)} $</b><small>cena × počet akcií</small></div><div><span>Čistý dluh</span><b>${compact(netDebt)} $</b><small>${Number(netDebt)<=0?'více hotovosti než dluhu':'dluh po odečtení hotovosti'}</small></div></div><p class="score-note">${fund?`Finanční zdraví: ${reasons.join(', ')||'bez jasné převahy'}. Násobky nejsou samy o sobě signál k nákupu.`:'Server zatím tento finanční snapshot nevytvořil.'}</p>`;
  }
  function dailyReturns(rows){const out=[];for(let i=1;i<(rows||[]).length;i++){const a=Number(rows[i-1]?.[4]),b=Number(rows[i]?.[4]);if(a>0&&b>0)out.push({d:rows[i][0],r:b/a-1});}return out;}
  function std(vals){if(vals.length<2)return null;const avg=vals.reduce((a,b)=>a+b,0)/vals.length;return Math.sqrt(vals.reduce((a,b)=>a+(b-avg)**2,0)/(vals.length-1));}
  function renderRiskPanel(bars,spyBars){
    if(!Array.isArray(bars)||bars.length<30){$('#riskPanel').innerHTML='<div class="panel-head"><div><p class="eyebrow">RIZIKOVÝ PANEL</p><h2>Data se připravují</h2></div></div><div class="empty-state">Pro spolehlivější výpočet je potřeba alespoň 30 denních svíček.</div>';return;}
    const recent=(bars||[]).slice(-253),rets=dailyReturns(recent),vol=std(rets.map(x=>x.r)),annualVol=ok(vol)?vol*Math.sqrt(252):null;let peak=null,maxDd=0;for(const r of recent){const c=Number(r[4]);if(!c)continue;peak=peak===null?c:Math.max(peak,c);maxDd=Math.min(maxDd,c/peak-1);}const atrRows=recent.slice(-15);let tr=[];for(let i=1;i<atrRows.length;i++){const h=+atrRows[i][2],l=+atrRows[i][3],pc=+atrRows[i-1][4];tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)));}const atr=tr.length?tr.reduce((a,b)=>a+b,0)/tr.length:null,last=Number(recent.at(-1)?.[4]),atrPct=last&&atr?atr/last:null;
    const stockMap=new Map(rets.map(x=>[x.d,x.r])),paired=dailyReturns((spyBars||[]).slice(-253)).filter(x=>stockMap.has(x.d)).map(x=>[stockMap.get(x.d),x.r]);let beta=null;if(paired.length>20){const am=paired.reduce((a,x)=>a+x[0],0)/paired.length,bm=paired.reduce((a,x)=>a+x[1],0)/paired.length,cov=paired.reduce((a,x)=>a+(x[0]-am)*(x[1]-bm),0)/(paired.length-1),variance=paired.reduce((a,x)=>a+(x[1]-bm)**2,0)/(paired.length-1);beta=variance?cov/variance:null;}
    const perf=n=>recent.length>n&&Number(recent.at(-1)?.[4])&&Number(recent.at(-1-n)?.[4])?Number(recent.at(-1)[4])/Number(recent.at(-1-n)[4])-1:null,riskPoints=(Number(annualVol)>.5?3:Number(annualVol)>.3?2:1)+(maxDd<-.4?3:maxDd<-.2?2:1)+(Number(beta)>1.5?2:Number(beta)>1?1:0),label=riskPoints>=7?'Vysoké':riskPoints>=4?'Zvýšené':'Mírné';
    $('#riskPanel').innerHTML=`<div class="panel-head"><div><p class="eyebrow">RIZIKOVÝ PANEL</p><h2>Kolísání a propady</h2></div><span class="risk-label ${riskPoints>=7?'danger':riskPoints>=4?'warn':'safe'}">${label}</span></div><div class="valuation-grid risk-grid"><div><span>Volatilita</span><b>${ratioPct(annualVol)}</b><small>roční přepočet</small></div><div><span>Max. propad</span><b class="down">${ratioPct(maxDd)}</b><small>z vrcholu za rok</small></div><div><span>Beta vs. SPY</span><b>${ok(beta)?num(beta,2):'—'}</b><small>${Number(beta)>1?'kolísá více než trh':'vůči trhu'}</small></div><div><span>ATR (14)</span><b>${money(atr)}</b><small>${ratioPct(atrPct)} denní ceny</small></div><div><span>Výnos 1 měsíc</span><b class="${cls(perf(21))}">${ratioPct(perf(21))}</b><small>21 obchodních dní</small></div><div><span>Výnos 1 rok</span><b class="${cls(perf(252))}">${ratioPct(perf(252))}</b><small>252 obchodních dní</small></div></div><p class="score-note">Beta a volatilita jsou počítané z denních zavíracích cen. Minulý pohyb nezaručuje budoucí výsledek.</p>`;
  }
  function renderDetailWatch(){const b=$('#detailWatch'),on=state.watch.includes(state.selected);b.textContent=on?'★':'☆';b.classList.toggle('on',on);b.setAttribute('aria-label',`${on?'Odebrat':'Přidat'} ${state.selected||''}`);}
  $('#detailWatch').addEventListener('click',()=>state.selected&&toggleWatch(state.selected));
  function aggregateIntraday(rows,minutes){
    const step=minutes*60000,buckets=new Map();
    for(const row of rows||[]){if(!Array.isArray(row)||row.length<6)continue;const ts=new Date(row[0]).getTime();if(!Number.isFinite(ts))continue;const key=Math.floor(ts/step)*step,old=buckets.get(key);if(!old)buckets.set(key,{timestamp:key,open:+row[1],high:+row[2],low:+row[3],close:+row[4],volume:+row[5]||0});else{old.high=Math.max(old.high,+row[2]);old.low=Math.min(old.low,+row[3]);old.close=+row[4];old.volume+=+row[5]||0;}}
    return [...buckets.values()].sort((a,b)=>a.timestamp-b.timestamp);
  }
  function dailyChartData(rows){return (rows||[]).filter(r=>Array.isArray(r)&&r.length>=6).map(r=>({timestamp:new Date(`${r[0]}T16:00:00-04:00`).getTime(),open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]||0})).filter(r=>Number.isFinite(r.timestamp));}
  function chartStyles(){const light=document.documentElement.classList.contains('light'),line=light?'#dbe3ee':'#21334d',text=light?'#63718a':'#8fa0b8',bg=light?'#ffffff':'#0b1422';return {bg,styles:{grid:{horizontal:{color:line},vertical:{color:line}},candle:{bar:{upColor:'#34d27b',downColor:'#ff6675',noChangeColor:text,upBorderColor:'#34d27b',downBorderColor:'#ff6675',noChangeBorderColor:text,upWickColor:'#34d27b',downWickColor:'#ff6675',noChangeWickColor:text},tooltip:{text:{color:text}}},indicator:{lines:[{color:'#5d8dff'},{color:'#f5b74c'},{color:'#36d1c4'},{color:'#b874ff'},{color:'#ff6675'}],tooltip:{text:{color:text}}},xAxis:{axisLine:{color:line},tickLine:{color:line},tickText:{color:text}},yAxis:{axisLine:{color:line},tickLine:{color:line},tickText:{color:text}},separator:{color:line,activeBackgroundColor:line},crosshair:{horizontal:{line:{color:text},text:{backgroundColor:'#21334d'}},vertical:{line:{color:text},text:{backgroundColor:'#21334d'}}}}};}
  function renderMarketChart(ticker){
    const box=$('#priceChart');$('#chartTitle').textContent=`${ticker} · detailní vývoj ceny`;if(state.chart){try{window.klinecharts?.dispose(state.chart);}catch{}state.chart=null;}box.innerHTML='';
    const interval=state.chartInterval,minutes=interval==='D'?null:Number(interval),bars=interval==='D'?dailyChartData(state.detailBars):aggregateIntraday(state.detailIntraday,minutes);const shown=interval==='D'?bars.slice(-400):bars;
    if(shown.length<2){$('#chartMeta').textContent=interval==='D'?'Denní historie není dostupná':'Minutová historie se připravuje po nasazení';renderChart(state.detailBars);return;}
    if(!window.klinecharts){$('#chartMeta').textContent='Grafová knihovna se nenačetla – zobrazuji základní graf';renderChart(state.detailBars);return;}
    try{
      const theme=chartStyles();box.style.background=theme.bg;window.klinecharts.registerLocale('cs-CZ',{time:'Čas',open:'Otevření',high:'Maximum',low:'Minimum',close:'Zavření',volume:'Objem',change:'Změna',turnover:'Obrat'});const chart=window.klinecharts.init(box);if(!chart)throw new Error('Graf nelze inicializovat');state.chart=chart;chart.setLocale('cs-CZ');chart.setTimezone('America/New_York');chart.setStyles(theme.styles);const last=shown.at(-1)?.close||0;chart.setPriceVolumePrecision(last<1?4:2,0);const indicator=state.chartIndicator;if(indicator){if(['MA','EMA','BOLL'].includes(indicator))chart.createIndicator(indicator,false,{id:'candle_pane'});else chart.createIndicator(indicator,false,{height:125,minHeight:80});}chart.applyNewData(shown);chart.scrollToRealTime();$('#chartMeta').textContent=`${shown.length} svíček · interval ${interval==='D'?'1D':interval+'m'} · data přibližně 15 min zpožděná`;
    }catch(e){console.error('KLineChart:',e);state.chart=null;$('#chartMeta').textContent='Pokročilý graf se nepodařilo vykreslit';renderChart(state.detailBars);}
  }
  function renderChart(rows){
    const data=(rows||[]).slice(-252).filter(r=>ok(r[4]));if(data.length<2){$('#priceChart').innerHTML='<div class="empty-state">Cenová historie zatím není dostupná.</div>';return;}
    const vals=data.map(r=>+r[4]),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,w=900,h=300,p=20;const pts=vals.map((v,i)=>`${p+i/(vals.length-1)*(w-p*2)},${p+(max-v)/range*(h-p*2)}`).join(' ');const up=vals.at(-1)>=vals[0],color=up?'var(--green)':'var(--red)';
    const grid=[0,.25,.5,.75,1].map(x=>`<line x1="${p}" y1="${p+x*(h-p*2)}" x2="${w-p}" y2="${p+x*(h-p*2)}" stroke="var(--line)" stroke-width="1"/><text x="${w-p}" y="${p+x*(h-p*2)-5}" text-anchor="end" fill="var(--muted)" font-size="11">${money(max-x*range)}</text>`).join('');
    $('#priceChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Cenový graf"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".28"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${p},${h-p} ${pts} ${w-p},${h-p}" fill="url(#fill)"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="3" vector-effect="non-scaling-stroke"/></svg>`;
  }
  $('#chartIntervals').addEventListener('click',e=>{const b=e.target.closest('[data-interval]');if(!b||!state.selected)return;state.chartInterval=b.dataset.interval;$$('#chartIntervals button').forEach(x=>x.classList.toggle('active',x===b));renderMarketChart(state.selected);});
  $('#chartIndicator').value=state.chartIndicator;$('#chartIndicator').addEventListener('change',e=>{state.chartIndicator=e.target.value;STORE.set('mt_chart_indicator',state.chartIndicator);if(state.selected)renderMarketChart(state.selected);});
  $('#expandChart').addEventListener('click',()=>{const panel=$('#chartPanel'),on=!panel.classList.contains('fullscreen');panel.classList.toggle('fullscreen',on);$('#expandChart').setAttribute('aria-expanded',String(on));$('#expandChart').textContent=on?'✕ Zavřít celý graf':'⛶ Celá obrazovka';document.body.style.overflow=on?'hidden':'';setTimeout(()=>window.dispatchEvent(new Event('resize')),60);});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#chartPanel').classList.contains('fullscreen'))$('#expandChart').click();});
  $('#chartResizer').addEventListener('pointerdown',e=>{e.preventDefault();const panel=$('#chartPanel'),start=e.clientY,startHeight=$('#priceChart').getBoundingClientRect().height;document.body.classList.add('chart-dragging');const move=ev=>{const h=Math.max(300,Math.min(900,startHeight+ev.clientY-start));panel.style.setProperty('--chart-height',`${h}px`);};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);document.body.classList.remove('chart-dragging');STORE.set('mt_chart_height',Math.round($('#priceChart').getBoundingClientRect().height));window.dispatchEvent(new Event('resize'));};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up);});
  const savedChartHeight=Number(STORE.get('mt_chart_height',520));if(savedChartHeight>=300&&savedChartHeight<=900)$('#chartPanel').style.setProperty('--chart-height',`${savedChartHeight}px`);
  window.addEventListener('resize',()=>state.chart?.resize());
  function groupTrades(rows){const m=new Map();for(const r of rows){const k=`${r.a||''}|${r.k||''}|${r.o||''}`;const g=m.get(k)||{...r,value:0,shares:0};g.value+=(r.s||0)*(r.p||0);g.shares+=r.s||0;m.set(k,g);}return [...m.values()];}
  function renderDetailInsiders(rows){const list=groupTrades(rows).filter(r=>['P','S'].includes(r.k)).slice(0,9);$('#detailInsiders').innerHTML=list.length?list.map(tradeCard).join(''):'<div class="empty-state">Pro tento titul nejsou v uloženém období dostupné insider obchody.</div>';}
  function tradeCard(r){const buy=r.k==='P'||r.ad==='A',value=r.value||((r.s||0)*(r.p||0));return `<article class="data-card"><div class="card-top"><span class="badge ${buy?'buy':'sell'}">${buy?'Nákup':'Prodej'}</span><span>${esc(r.t||'')}</span><strong>${compact(value)} $</strong></div><h3>${esc(title(r.o||'Neznámý insider'))}</h3><p>${esc(r.r||r.i||'')} · obchod ${date(r.d)} · zveřejněno ${date(r.f)}</p><div class="card-tags">${r.pl?'<span class="badge">Plán 10b5-1</span>':''}${r.sc?`<span class="badge">Skóre ${esc(r.sc)}/10</span>`:''}</div>${r.u?`<a href="${esc(r.u)}" target="_blank" rel="noopener noreferrer">Originální hlášení SEC →</a>`:''}</article>`;}

  const INS_HINT={buys:'Nákupy na volném trhu, za které insider zaplatil vlastními penězi. Často mají vyšší vypovídací hodnotu než prodeje.',sells:'Velké prodeje mohou souviset s daněmi, diverzifikací nebo předem nastaveným plánem. Samy o sobě nejsou automaticky negativním signálem.',f144:'Form 144 oznamuje záměr prodat akcie ještě před uskutečněním prodeje.',f13d:'Schedule 13D zveřejňuje podíl nad 5 %, pokud investor může chtít firmu aktivně ovlivňovat.'};
  async function loadInsiders(){const mode=state.insiderMode;$('#insiderExplain').textContent=INS_HINT[mode];const box=$('#insiderFeed');box.innerHTML='<div class="skeleton h40"></div>';try{const file={buys:'feed-buys.json',sells:'feed-sells.json',f144:'f144.json',f13d:'f13d.json'}[mode];const rows=state.insiderData[mode]||await data(file);state.insiderData[mode]=rows||[];if(mode==='buys')renderClusterBuys(rows||[]);else if(state.insiderData.buys)renderClusterBuys(state.insiderData.buys);box.innerHTML=(rows||[]).length?(mode==='f144'?(rows||[]).map(form144Card).join(''):mode==='f13d'?(rows||[]).map(form13dCard).join(''):groupTrades(rows||[]).slice(0,120).map(tradeCard).join('')):'<div class="empty-state">Žádná aktuální hlášení.</div>';}catch{box.innerHTML='<div class="empty-state">Data se nepodařilo načíst.</div>';}}
  function renderClusterBuys(rows){
    const groups=new Map();for(const r of rows){if(!r.t)continue;const g=groups.get(r.t)||{ticker:r.t,company:r.i,value:0,names:new Set(),trades:0,last:null};g.value+=(Number(r.s)||0)*(Number(r.p)||0);g.trades++;if(r.o)g.names.add(r.o);if(!g.last||new Date(r.d)>new Date(g.last))g.last=r.d;groups.set(r.t,g);}const clusters=[...groups.values()].filter(g=>g.names.size>=2).sort((a,b)=>b.names.size-a.names.size||b.value-a.value).slice(0,8);
    $('#clusterBuys').innerHTML=clusters.length?clusters.map(g=>`<button class="cluster-card" data-open="${esc(g.ticker)}"><span><b>${esc(g.ticker)}</b><small>${esc(g.company||'')}</small></span><strong>${g.names.size} insiderů</strong><em>${compact(g.value)} $ celkem · ${g.trades} obchodů</em><small>Poslední ${date(g.last)}</small></button>`).join(''):'<div class="empty-state">V aktuálním období není potvrzený nákup více různých insiderů stejné firmy.</div>';
  }
  $('#insiderFilters').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;state.insiderMode=b.dataset.mode;$$('#insiderFilters button').forEach(x=>x.classList.toggle('active',x===b));loadInsiders();});
  function form144Card(r){return `<article class="data-card"><div class="card-top"><span class="badge sell">Plánovaný prodej</span><span>${esc(r.t||'')}</span><strong>${compact(r.v)} $</strong></div><h3>${esc(title(r.o||'Insider'))}</h3><p>${esc(r.r||r.i||'')} · plán kolem ${date(r.d)} · podáno ${date(r.f)}</p><div class="card-tags">${r.pl?`<span class="badge">10b5-1 od ${date(r.pl)}</span>`:'<span class="badge sell">Bez uvedeného plánu</span>'}</div>${r.u?`<a href="${esc(r.u)}" target="_blank" rel="noopener noreferrer">Originální hlášení SEC →</a>`:''}</article>`;}
  function form13dCard(r){return `<article class="data-card"><div class="card-top"><span class="badge buy">${r.am?'Změna podílu':'Nový podíl'}</span><span>${esc(r.t||'')}</span><strong>${ok(r.pct)?num(r.pct,1)+' %':''}</strong></div><h3>${esc(title(r.o||'Investor'))}</h3><p>${esc(r.i||'')} · podáno ${date(r.f)}</p>${r.pu?`<p style="margin-top:10px">${esc(r.pu)}</p>`:''}${r.u?`<a href="${esc(r.u)}" target="_blank" rel="noopener noreferrer">Originální hlášení SEC →</a>`:''}</article>`;}

  async function loadGurus(){const box=$('#guruList');box.innerHTML='<div class="skeleton h40"></div>';try{const gurus=state.gurus.length?state.gurus:await data('gurus.json');state.gurus=gurus||[];buildSignalIndexes();renderSmartMoney();}catch{box.innerHTML='<div class="empty-state">Data se nepodařilo načíst.</div>';}}
  function guruCard(g){const all=[...(g.pos||[])],changed=all.filter(p=>p.ch&&p.ch!=='same').length,pos=all.filter(p=>p.ch!=='out').sort((a,b)=>(b.v||0)-(a.v||0)).slice(0,8),max=Math.max(1,...pos.map(p=>p.v||0));return `<article class="panel guru-card"><div class="guru-title"><div><h2>${esc(g.label||g.fund||'Investor')}</h2><p>${esc(g.fund||'')} · stav ${date(g.period)}</p></div><span>${changed} změn</span></div><div class="guru-holdings">${pos.map(p=>`<div class="holding-row"><button class="link-btn" data-open="${esc(p.t||'')}">${esc(p.t||'—')}</button><div class="holding-bar"><i style="--w:${(p.w||((p.v||0)/max*100))}%"></i></div><b>${ok(p.w)?num(p.w,1)+' %':compact(p.v)+' $'}</b></div>`).join('')}</div></article>`;}
  function renderSmartMoney(){
    const moves=[];for(const g of state.gurus)for(const p of g.pos||[])if(p.ch&&p.ch!=='same')moves.push({g,p});const filtered=state.guruMode==='all'?moves:moves.filter(x=>x.p.ch===state.guruMode);filtered.sort((a,b)=>(b.p.v||b.p.pv||0)-(a.p.v||a.p.pv||0));
    const counts={new:moves.filter(x=>x.p.ch==='new').length,add:moves.filter(x=>x.p.ch==='add').length,cut:moves.filter(x=>x.p.ch==='cut').length,out:moves.filter(x=>x.p.ch==='out').length};
    $('#smartMetrics').innerHTML=`<article class="metric-card"><span>Sledovaní správci</span><strong>${state.gurus.length}</strong><small>ve veřejných 13F</small></article><article class="metric-card"><span>Nové pozice</span><strong class="up">${counts.new}</strong><small>od minulého kvartálu</small></article><article class="metric-card"><span>Navýšení</span><strong class="up">${counts.add}</strong><small>pozic</small></article><article class="metric-card"><span>Ukončené</span><strong class="down">${counts.out}</strong><small>pozice</small></article>`;
    $('#smartMoves').innerHTML=`<div class="smart-table-head"><span>Titul</span><span>Investor</span><span>Změna kusů</span><span>Váha</span><span>Hodnota</span></div>${filtered.slice(0,80).map(({g,p})=>{const delta=ok(p.s)&&ok(p.ps)?(p.s-p.ps):null;const deltaPct=ok(delta)&&p.ps?delta/p.ps*100:null;return `<div class="smart-row"><button class="link-btn" data-open="${esc(p.t||'')}">${esc(p.t||'—')}</button><span>${esc(g.label||g.fund||'Investor')}</span><span class="${cls(delta)}">${p.ch==='new'?'Nová':p.ch==='out'?'Ukončená':ok(deltaPct)?pct(deltaPct):changeLabel(p.ch)}</span><span>${ok(p.w)?num(p.w,2)+' %':'—'}</span><b>${compact(p.v||p.pv)} $</b></div>`;}).join('')||'<div class="empty-state">Žádné pohyby v této kategorii.</div>'}`;
    $('#guruList').innerHTML=state.gurus.length?state.gurus.map(guruCard).join(''):'<div class="empty-state">Data 13F se připravují.</div>';
  }
  $('#guruFilters').addEventListener('click',e=>{const b=e.target.closest('[data-guru-mode]');if(!b)return;state.guruMode=b.dataset.guruMode;$$('#guruFilters button').forEach(x=>x.classList.toggle('active',x===b));renderSmartMoney();});
  function changeLabel(ch){return {new:'Nová pozice',add:'Navýšení',cut:'Snížení',out:'Ukončená pozice'}[ch]||'Změna';}

  function addCompare(){const input=$('#compareInput'),ticker=input.value.trim().toUpperCase().replace(/[^A-Z0-9.\-]/g,'');if(!ticker)return;if(!state.byTicker.has(ticker)){toast('Ticker není v aktuálním tržním snapshotu');return;}if(!state.compare.includes(ticker)){if(state.compare.length>=4){toast('Porovnat lze nejvýše 4 tituly');return;}state.compare.push(ticker);}input.value='';STORE.set('mt_compare_v1',state.compare);renderCompare();}
  function renderCompare(){
    state.compare=state.compare.filter(t=>state.byTicker.has(t)).slice(0,4);STORE.set('mt_compare_v1',state.compare);$('#compareChips').innerHTML=state.compare.map(t=>`<span>${esc(t)}<button data-compare-remove="${esc(t)}" aria-label="Odebrat ${esc(t)}">×</button></span>`).join('');
    const stocks=state.compare.map(t=>state.byTicker.get(t)).filter(Boolean),box=$('#compareTable');if(stocks.length<2){box.innerHTML='<div class="empty-state">Přidej alespoň dva tickery pro porovnání.</div>';return;}
    const row=(label,fn,klass=()=>'',hint='')=>`<tr><th>${esc(label)}${hint?`<small>${esc(hint)}</small>`:''}</th>${stocks.map(s=>`<td class="${klass(s)}">${fn(s)}</td>`).join('')}</tr>`;
    box.innerHTML=`<table class="compare-table"><thead><tr><th>Metrika</th>${stocks.map(s=>`<th><button class="compare-symbol" data-open="${esc(s.ticker)}"><span class="mini-logo">${esc(s.ticker.slice(0,2))}</span><b>${esc(s.ticker)}</b><small>${esc(s.name||'')}</small></button></th>`).join('')}</tr></thead><tbody>${row('Cena',s=>`<b>${money(s.price)}</b>`)}${row('Dnes',s=>`<b>${pct(s.change)}</b>`,s=>cls(s.change))}${row('Objem',s=>compact(s.volume))}${row('Relativní objem',s=>rel(s.rel_volume),s=>Number(s.rel_volume)>=1.5?'up':'')}${row('52týdenní pozice',s=>`${num(yearPosition(s),0)} %`)}${row('Insider nákupy',s=>{const x=state.insiderSignals.get(s.ticker);return x?`${x.people} lidí · ${compact(x.value)} $`:'Žádné';})}${row('13F signály',s=>{const x=state.guruSignals.get(s.ticker);return x?`${x.new} nové · ${x.add} navýšené`:'Žádné';})}${row('MarketTrace skóre',s=>{const n=scoreStock(s);return `<span class="signal ${signalClass(n)}">${n}/100</span><small>${esc(scoreVerdict(s).split('–')[1]||'')}</small>`;})}</tbody></table>`;
  }
  $('#compareAdd').addEventListener('click',addCompare);$('#compareInput').addEventListener('keydown',e=>{if(e.key==='Enter')addCompare();});

  function renderPortfolio(){
    const groups=new Map();for(const l of state.portfolio){const g=groups.get(l.ticker)||{ticker:l.ticker,lots:[],qty:0,cost:0};g.lots.push(l);g.qty+=l.qty;g.cost+=l.qty*l.price;groups.set(l.ticker,g);}let value=0,cost=0,day=0,missing=0;
    for(const g of groups.values()){const s=state.byTicker.get(g.ticker);g.current=s?.price;g.value=ok(g.current)?g.qty*g.current:null;g.pl=ok(g.value)?g.value-g.cost:null;if(ok(g.value)){value+=g.value;cost+=g.cost;day+=g.qty*(g.current-(s.previous_close||g.current));}else missing++;}
    const pl=value-cost;$('#portfolioMetrics').innerHTML=`<article class="metric-card"><span>Hodnota portfolia</span><strong>${money(value)}</strong><small>${groups.size} titulů</small></article><article class="metric-card"><span>Zisk / ztráta</span><strong class="${cls(pl)}">${money(pl)}</strong><small class="${cls(pl)}">${pct(cost?pl/cost*100:null)}</small></article><article class="metric-card"><span>Dnes</span><strong class="${cls(day)}">${money(day)}</strong><small>podle posledního snapshotu</small></article><article class="metric-card"><span>Bez aktuální ceny</span><strong>${missing}</strong><small>pozic</small></article>`;
    const box=$('#portfolioList');box.innerHTML=groups.size?[...groups.values()].sort((a,b)=>(b.value||0)-(a.value||0)).map(g=>`<div class="portfolio-row"><div><button class="link-btn" data-open="${esc(g.ticker)}"><b>${esc(g.ticker)}</b></button><small>${num(g.qty,4)} ks · průměr ${money(g.cost/g.qty)}</small></div><div><small>Aktuální cena</small><b>${money(g.current)}</b></div><div><small>Hodnota</small><b>${money(g.value)}</b></div><div><small>Zisk / ztráta</small><b class="${cls(g.pl)}">${money(g.pl)}</b></div><div><small>Výnos</small><b class="${cls(g.pl)}">${pct(g.cost?g.pl/g.cost*100:null)}</b></div><button data-delete-group="${esc(g.ticker)}" aria-label="Smazat ${esc(g.ticker)}">×</button></div>`).join(''):'<div class="empty-state">Portfolio je zatím prázdné. Přidej první nákup vlevo.</div>';
  }
  $('#portfolioForm').addEventListener('submit',e=>{e.preventDefault();const ticker=$('#portfolioTicker').value.trim().toUpperCase().replace(/[^A-Z0-9.\-]/g,''),qty=parseFloat($('#portfolioQty').value),price=parseFloat($('#portfolioPrice').value);if(!ticker||!(qty>0)||!(price>0))return;state.portfolio.push({id:crypto.randomUUID?.()||String(Date.now()),ticker,qty,price,date:$('#portfolioDate').value||new Date().toISOString().slice(0,10)});STORE.set('mt_port_v2',state.portfolio);e.target.reset();$('#portfolioDate').value=new Date().toISOString().slice(0,10);renderPortfolio();toast(`${ticker} přidána do portfolia`);});
  $('#exportPortfolio').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),lots:state.portfolio},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`markettrace-portfolio-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);});
  $('#importPortfolio').addEventListener('change',async e=>{try{const j=JSON.parse(await e.target.files[0].text());if(!Array.isArray(j.lots))throw 0;state.portfolio=j.lots.filter(x=>x.ticker&&x.qty>0&&x.price>0);STORE.set('mt_port_v2',state.portfolio);renderPortfolio();toast('Portfolio bylo importováno');}catch{toast('Soubor není platná záloha MarketTrace');}e.target.value='';});

  document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){e.preventDefault();openDetail(open.dataset.open);return;}const w=e.target.closest('[data-watch]');if(w){toggleWatch(w.dataset.watch);return;}const u=e.target.closest('[data-unwatch]');if(u){toggleWatch(u.dataset.unwatch);return;}const cr=e.target.closest('[data-compare-remove]');if(cr){state.compare=state.compare.filter(t=>t!==cr.dataset.compareRemove);STORE.set('mt_compare_v1',state.compare);renderCompare();return;}const d=e.target.closest('[data-delete-group]');if(d){if(confirm(`Smazat všechny nákupy ${d.dataset.deleteGroup}?`)){state.portfolio=state.portfolio.filter(x=>x.ticker!==d.dataset.deleteGroup);STORE.set('mt_port_v2',state.portfolio);renderPortfolio();}}});
  $('#themeBtn').addEventListener('click',()=>{document.documentElement.classList.toggle('light');STORE.set('mt_theme',document.documentElement.classList.contains('light')?'light':'dark');if(state.view==='detail'&&state.selected)renderMarketChart(state.selected);});if(STORE.get('mt_theme','dark')==='light')document.documentElement.classList.add('light');
  function title(v){return String(v||'').toLowerCase().replace(/\b\p{L}/gu,m=>m.toUpperCase());}

  async function boot(){
    $('#portfolioDate').value=new Date().toISOString().slice(0,10);renderWatch();
    try{const m=await data('market.json',true);state.marketMeta=m;state.market=(m.symbols||[]).map(s=>({...s,score:scoreStock(s)}));state.byTicker=new Map(state.market.map(s=>[s.ticker,s]));const age=Date.now()-new Date(m.updated).getTime(),stale=age>45*60000;$('#feedStatus').className=`feed-status ${stale?'stale':'live'}`;$('#feedStatus b').textContent=stale?'Poslední dostupná data':'Data připojena';$('#updatedAt').textContent=`Poslední aktualizace ${dateTime(m.updated)} · zpoždění přibližně ${m.delay||15} min`;renderWatch();renderPulse();renderMetrics();renderStocks();renderHighlights();renderPortfolio();
    }catch(e){$('#feedStatus').className='feed-status error';$('#feedStatus b').textContent='Data nejsou dostupná';$('#stockRows').innerHTML='<tr><td colspan="8"><div class="empty-state">Tržní snapshot se právě připravuje. Zkus stránku obnovit za několik minut.</div></td></tr>';console.error(e);}
    const h=decodeURIComponent(location.hash.slice(1)),route=h.toLowerCase();if(!route||route==='prehled'||route==='overview')setView('overview');else if(['insiders','gurus','compare','portfolio'].includes(route))setView(route);else if(/^[A-Z][A-Z0-9.\-]{0,9}$/.test(h.toUpperCase()))openDetail(h.toUpperCase());
  }

  async function openBuysSheet(){
    let sheet=$('#buysSheet');
    if(!sheet){sheet=document.createElement('div');sheet.id='buysSheet';sheet.className='sheet';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');document.body.appendChild(sheet);
      sheet.addEventListener('click',e=>{if(e.target===sheet||e.target.closest('[data-close]')){closeBuysSheet();return;}const c=e.target.closest('[data-sheet-ticker]');if(c&&!e.target.closest('a')){closeBuysSheet();openDetail(c.dataset.sheetTicker);}});
      document.addEventListener('keydown',e=>{if(e.key==='Escape'&&sheet.classList.contains('open'))closeBuysSheet();});}
    const watched=state.watch.length>0,set=new Set(watched?state.watch:state.market.map(s=>s.ticker));
    sheet.innerHTML=`<div class="sheet-panel"><div class="panel-head"><div><p class="eyebrow">SEC FORM 4 · POSLEDNÍCH 45 DNÍ</p><h2>Insider nákupy ${watched?'u sledovaných':'u titulů v přehledu'}</h2></div><button class="secondary-btn" data-close type="button">Zavřít</button></div><div class="sheet-body"><div class="skeleton h40"></div></div></div>`;
    sheet.classList.add('open');document.body.classList.add('sheet-lock');
    try{const rows=(await data('feed-buys.json'))||[];const list=rows.filter(r=>set.has(r.t)).sort((a,b)=>String(b.f||'').localeCompare(String(a.f||''))||((b.s||0)*(b.p||0))-((a.s||0)*(a.p||0)));
      $('.sheet-body',sheet).innerHTML=list.length?`<p class="sheet-note">${list.length} ${list.length===1?'nákup':list.length<5?'nákupy':'nákupů'} · klepnutím otevřete detail akcie</p><div class="cards-grid">${list.map(r=>`<div class="sheet-card" data-sheet-ticker="${esc(r.t)}">${tradeCard(r)}</div>`).join('')}</div>`:'<div class="empty-state">Za posledních 45 dní tu insideři nic nenakoupili.</div>';}
    catch{$('.sheet-body',sheet).innerHTML='<div class="empty-state">Nákupy se nepodařilo načíst. Zkus to za chvíli.</div>';}
  }
  function closeBuysSheet(){const sh=$('#buysSheet');if(sh)sh.classList.remove('open');document.body.classList.remove('sheet-lock');}
  $('#marketMetrics').addEventListener('click',e=>{if(e.target.closest('[data-open-buys]'))openBuysSheet();});
  $('#marketMetrics').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-open-buys]')){e.preventDefault();openBuysSheet();}});
  window.MT_openBuys=openBuysSheet;
  boot();
})();
