const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function load(lang){const values=new Map([['mt_language',lang]]);const document={documentElement:{lang:'cs'},querySelectorAll:()=>[],createTreeWalker:()=>({nextNode:()=>false})};const context={localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},document,window:{},Node:{TEXT_NODE:3,ELEMENT_NODE:1},NodeFilter:{SHOW_TEXT:4},MutationObserver:class{observe(){}}};vm.runInNewContext(fs.readFileSync('i18n.js','utf8'),context);return context.window.MTI18n;}
for(const [lang,overview,smartMoney,emptyWatchlist,locale] of [['en','Overview','Smart Money','The watchlist is empty.','en-US'],['de','Übersicht','Intelligentes Kapital','Die Beobachtungsliste ist leer.','de-DE'],['it','Panoramica','Capitale intelligente','La lista di controllo è vuota.','it-IT'],['fr','Aperçu','Capitaux avisés','La liste de suivi est vide.','fr-FR']])test(`${lang} translates the main interface`,()=>{const i=load(lang);assert.equal(i.text('Přehled'),overview);assert.equal(i.text('Smart Money'),smartMoney);assert.equal(i.text('Watchlist je prázdný.'),emptyWatchlist);assert.notEqual(i.text('DNEŠNÍ RADAR'),'DNEŠNÍ RADAR');assert.notEqual(i.text('MAKRO A POLITIKA'),'MAKRO A POLITIKA');assert.notEqual(i.text(' 42 analytiků '),' 42 analytiků ');assert.equal(i.locale(),locale);});
for(const lang of ['en','de','it','fr'])test(`${lang} translates earnings calendar`,()=>{const i=load(lang);assert.notEqual(i.text('VÝSLEDKOVÝ KALENDÁŘ'),'VÝSLEDKOVÝ KALENDÁŘ');assert.notEqual(i.text('Pro sledované tituly zatím nejsou dostupné výsledky na příštích 7 dní.'),'Pro sledované tituly zatím nejsou dostupné výsledky na příštích 7 dní.');});
for(const lang of ['en','de','it','fr'])test(`${lang} translates market regime and account feedback`,()=>{const i=load(lang);for(const label of ['TRŽNÍ REŽIM','Má trh vítr v zádech?','Dnešní režim','Neutrální','Moje sledované','Celý přehled','Přihlašuji…','Přístup vyžaduje přihlášení','Účet se nepodařilo načíst','Ukládám…'])assert.notEqual(i.text(label),label);});
for(const lang of ['en','de','it','fr'])test(`${lang} translates risk and valuation detail`,()=>{const i=load(lang);for(const label of ['RIZIKOVÝ PANEL','Kolísání a propady','Finanční zdraví','VEŘEJNÁ HLÁŠENÍ','Aktivita insiderů'])assert.notEqual(i.text(label),label);});
for(const lang of ['de','it','fr'])test(`${lang} translates dynamically rendered detail labels`,()=>{const i=load(lang);for(const label of ['KLÍČOVÉ HODNOTY','Denní minimum','20denní průměr','Relativní objem','VYSVĚTLITELNÉ SKÓRE','Skóre kombinuje trend, dnešní momentum, časově srovnatelný objem a aktuální veřejná hlášení SEC/13F. Chybějící RVOL dostává neutrální hodnotu. Není to doporučení k nákupu.','Minutová data se připravují','Co musí platit','Odebrat','Moje sledování'])assert.notEqual(i.text(label),label);});
test('Czech remains unchanged',()=>{const i=load('cs');assert.equal(i.text('Přehled'),'Přehled');assert.equal(i.locale(),'cs-CZ');});
test('language preference is validated',()=>{const {valid}=require('../src/preferences.cjs');for(const lang of ['cs','en','de','it','fr'])assert.equal(valid('mt_language',lang),true);assert.equal(valid('mt_language','es'),false);});
